#here we are stages we are going deal and --deps is dependencies
stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/opex.csv
    outs:
      - data/raw/opex.csv