#here we are stages we are going deal and --deps is dependencies
stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/opex.csv
    outs:
      - data/raw/opex.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/opex.csv
    outs:
      - data/processed/opextrain.csv
      - data/processed/opextest.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/opextrain.csv
      - data/processed/opextest.csv
      - src/train_and_evaluate.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics:
      - reports/scores.json:
          cache: False
      - reports/params.json:
          cache: False
    outs:
      - saved_models/model.joblib